### ISSUE TITLE
Environment Mappings: document position detection flawed

### ISSUE THREAD

**Issue by Druidefix** [vim-latex/vim-latex#83] opened 2017-03-06 12:37 UTC
Hello,

I must admit that I did not update my vim plugins for a very long time.

If I'm want to add a figure, I type 'figure' and then press `<F5>`. This automatically results in the [correct environment](http://vim-latex.sourceforge.net/documentation/latex-suite/environment-mappings.html) as described in the manual. Unfortunately with the current version 7df30fe this doesn't work for me.

It seems like this has something to do with the detection of the current position I'm editing, because I'm getting a `\usepackage{figure}` code as [mentioned in this question](https://tex.stackexchange.com/questions/53900).

I pinpointed the commit 6870264 from @gerw to cause the problems. If I use the current commit and revert the changed made at this old commit everything works fine.

I did not fully understand what exactly causes the problem, because I only notice the error in the [IEEE template](https://www.ieee.org/documents/IEEEtran.zip) `bare_conf.tex`. In other files the problem does not exist. Perhaps in the IEEE there are some special characters which fool the detection of the `\begin{document}`.

**Comment by gerw** [comment] 2017-03-06 19:27
The problem is the `\documentclass` (l. 349) in a comment after the `\begin{document}'. It would be possible to exclude comments, but this would be much slower. I will think about it.

**Comment by gerw** [comment] 2017-03-06 20:16
Should be fixed now (and should even be faster as before). Can you please check, whether it works for you?

**Comment by Druidefix** [comment] 2017-03-07 06:33
Thank you very much for the fast fix for my problem. This indeed solves it.

**Closed** 2017-03-07 07:34 UTC
