### ISSUE TITLE
Math-coloring after folding which should have regular coloring

### ISSUE THREAD

**Issue by albinahlback** [vim-latex/vim-latex#203] opened 2021-08-22 18:52 UTC
I am having problem with text after a folding being displayed in Neovim as math. Let me describe the problem by how to reproduce it:

1. Create the file that is at the bottom of post.
2. Open the file with a fresh session.
3. Open the `equation*`-fold.
4. Close the `equation*`-fold.
5. Insert `$math$` after `Insert double dollar sign with math inside:`.
6. Watch how `More text` is math-colored, as compared to the text-colored `Some text`.

This appears to happen when the file looks a certain way, as this was the MWE that I was able to create.

Let me know if you can't reproduce it.

```latex
\documentclass[a4paper,12pt,oneside,headsepline,draft]{scrartcl}

\input{packages}
\input{layout}
\input{shortcuts}
\input{shortcuts_this}


\newcommand{\headertitle}{{\normalfont%
  %% SHORT TITLE
}}
\newcommand{\headerauthors}{%
  XXX,
  XXX,
  XXX%
}
\title{%
  Title
}
\author{%
  XXX%
\and
  XXX%
\and
  XXX%
}
\date{\today\ at\ \thistime}

\begin{document}

Insert double dollar sign with math inside:
Some text
\begin{equation*}
  kajnds
\end{equation*}
More text


\begin{align*}
  \begin{psmatrix} * & * \\ 2 & -1 \end{psmatrix}
\;{}&=\;
  S T^2 S
\\
  \begin{psmatrix} * & * \\ -3 & -2 \end{psmatrix}
\;{}&=\;
  S T^2 S T^{-1} S
\\
  \begin{psmatrix} * & * \\ -5 & 3 \end{psmatrix}
\;{}&=\;
  S T^2 S T^{-1} S T^1 S
\\
  \begin{psmatrix} * & * \\ -5 & -2 \end{psmatrix}
\;{}&=\;
  S T^2 S T^{-2} S
\\
  \begin{psmatrix} * & * \\ 3 & -1 \end{psmatrix}
\;{}&=\;
  S T^3 S
\\
  \begin{psmatrix} * & * \\ -4 & -3 \end{psmatrix}
\;{}&=\;
  S T^3 S T^{-1} S
\\
  \begin{psmatrix} * & * \\ 4 & -1 \end{psmatrix}
\;{}&=\;
  S T^4 S
\\
  \begin{psmatrix} * & * \\ -5 & -4 \end{psmatrix}
\;{}&=\;
  S T^4 S T^{-1} S
\\
  \begin{psmatrix} * & * \\ 5 & -1 \end{psmatrix}
\;{}&=\;
  S T^5 S
\end{align*}

\begin{gather*}
  \gamma
\;\longmapsto\;
  \gamma (T^\alpha S)^{-1}
\;=\;
  \begin{pmatrix}
    * & *
  \\
    -d & d \alpha + c
  \end{pmatrix}
\tx{,}\qquad
  \alpha
\;=\;
  -\Biggl[ \frac{c}{d} \Biggr]
\tx{,}
\end{gather*}

\begin{gather*}
  -\Biggl[ \frac{c(\gamma T^\alpha S)}{d(\gamma T^\alpha S)} \Biggr]
\;=\;
  \Biggl[ \alpha + \frac{d(\gamma)}{c(\gamma)} \Biggr]
\tx{.}
\end{gather*}
\begin{gather*}
  \sgn(\alpha)
\;=\;
  \sgn\bigl( d(\gamma) / c(\gamma) \bigr)
\;=\;
  \sgn\bigl( [c(\gamma) / d(\gamma)] \bigr)
\;=\;
  \sgn(-\alpha_\ell)
\tx{,}
\end{gather*}

\end{document}

%% vim: spell spelllang=en_us
```

**Comment by gerw** [comment] 2021-08-22 19:13
Sorry, I am not able to reproduce. Does this also happens with vim? Can you try to use a minimal config? For debugging, I typically use
````
"gvim" -U NONE -u ~/.vim/vimrc_latex-suite
````
and `~/.vim/vimrc_latex-suite` includes `let &rtp = substitute(&rtp, '\.vim\>', '.vim/bundle/vim-latex-suite', 'g')`. This is useful, since only the latex suite is loaded with this config.

**Comment by albinahlback** [comment] 2021-08-22 19:36
With Neovim, and the script list (by running `:scriptname`)
```
  1: /etc/xdg/nvim/sysinit.vim
  2: /usr/share/nvim/archlinux.vim
  3: ~/.config/nvim/init.vim
  4: /usr/share/nvim/runtime/ftoff.vim
  5: ~/.config/nvim/bundle/Vundle.vim/autoload/vundle.vim
  6: ~/.config/nvim/bundle/Vundle.vim/autoload/vundle/config.vim
  7: /usr/share/nvim/runtime/ftplugin.vim
  8: /usr/share/nvim/runtime/indent.vim
  9: /usr/share/nvim/runtime/syntax/syntax.vim
 10: /usr/share/nvim/runtime/syntax/synload.vim
 11: /usr/share/nvim/runtime/syntax/syncolor.vim
 12: /usr/share/nvim/runtime/filetype.vim
 13: /usr/share/nvim/runtime/autoload/dist/ft.vim
 14: /usr/share/nvim/runtime/ftplugin/plaintex.vim
 15: /usr/share/nvim/runtime/ftplugin/initex.vim
 16: /usr/share/nvim/runtime/syntax/plaintex.vim
 17: /usr/share/nvim/runtime/syntax/initex.vim
 18: ~/.config/nvim/bundle/vim-latex/plugin/SyntaxFolds.vim
 19: ~/.config/nvim/bundle/vim-latex/plugin/filebrowser.vim
 20: ~/.config/nvim/bundle/vim-latex/plugin/imaps.vim
 21: ~/.config/nvim/bundle/vim-latex/plugin/remoteOpen.vim
 22: /usr/share/nvim/runtime/plugin/gzip.vim
 23: /usr/share/nvim/runtime/plugin/health.vim
 24: /usr/share/nvim/runtime/plugin/man.vim
 25: /usr/share/nvim/runtime/plugin/matchit.vim
 26: /usr/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
 27: /usr/share/nvim/runtime/plugin/matchparen.vim
 28: /usr/share/nvim/runtime/plugin/netrwPlugin.vim
 29: /usr/share/nvim/runtime/plugin/rplugin.vim
 30: /usr/share/nvim/runtime/plugin/shada.vim
 31: /usr/share/nvim/runtime/plugin/spellfile.vim
 32: /usr/share/nvim/runtime/plugin/tarPlugin.vim
 33: /usr/share/nvim/runtime/plugin/tohtml.vim
 34: /usr/share/nvim/runtime/plugin/tutor.vim
 35: /usr/share/nvim/runtime/plugin/zipPlugin.vim
 36: ~/.config/nvim/bundle/vim-latex/ftplugin/tex_latexSuite.vim
 37: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/main.vim
 38: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/texrc
 39: /usr/share/nvim/runtime/autoload/provider/python3.vim
 40: /usr/share/nvim/runtime/autoload/provider/pythonx.vim
 41: /usr/share/nvim/runtime/autoload/remote/host.vim
 42: /usr/share/nvim/runtime/autoload/provider/python.vim
 43: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/texproject.vim
 44: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/texmenuconf.vim
 45: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/envmacros.vim
 46: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/wizardfuncs.vim
 47: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/elementmacros.vim
 48: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/mathmacros.vim
 49: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/multicompile.vim
 50: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/compiler.vim
 51: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/folding.vim
 52: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/templates.vim
 53: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/custommacros.vim
 54: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/bibtex.vim
 55: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/brackets.vim
 56: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/smartspace.vim
 57: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/texviewer.vim
 58: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/version.vim
 59: ~/.config/nvim/bundle/vim-latex/ftplugin/latex-suite/packages.vim
 60: ~/test/main.tex.latexmain
 61: ~/.config/nvim/bundle/vim-latex/compiler/tex.vim
 62: /usr/share/nvim/runtime/ftplugin/tex.vim
 63: ~/.config/nvim/bundle/vim-latex/indent/tex.vim
 64: /usr/share/nvim/runtime/indent/tex.vim
 65: /usr/share/nvim/runtime/syntax/tex.vim
```
where `init.vim` is fully composed of
```vim
set nocompatible
filetype off
set rtp+=~/.config/nvim/bundle/Vundle.vim
call vundle#begin("~/.config/nvim/bundle")
Plugin 'gmarik/Vundle.vim'

Plugin 'vim-latex/vim-latex'

call vundle#end()
```
I am able to reproduce it. I am using Neovim version 0.5.0.

**Comment by albinahlback** [comment] 2021-08-22 19:41
Might be because I am using Neovim. Maybe folds work different in Neovim (I've had the feeling that Neovim runs faster than Vim for larger files)?

**Comment by gerw** [comment] 2021-08-23 05:46
Can you try it with vim?

**Comment by albinahlback** [comment] 2021-08-23 10:58
Yeah, I do not get that problem with `vim`.

**Comment by gerw** [comment] 2021-08-23 11:32
Then, this seems to be a problem with neovim and I 'vote' to close this issue.

**Closed** 2021-08-23 11:34 UTC
