### ISSUE TITLE
cite F9 autocomplete error

### ISSUE THREAD

**Issue by miccferr** [vim-latex/vim-latex#104] opened 2017-09-26 14:57 UTC
Hello,

I am having the an error whenever trying to autocomplete a `\cite{}` pressing `F9`.  The citation menu appears correctly, though empty, but then when I try to use any of the commands 9 i.e. `a(all) ` to display all citations I get the following:

```python
Error detected while processing function Tex_HandleBibShortcuts:
line   47:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
line   48:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
Error detected while processing function Tex_HandleBibShortcuts..Tex_DisplayBibList:
line   21:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
```

I am aware of similar closed issues such as #60 and #87 but I couldn't find any solution there.

I'm working with this minimal reproducible setup:

```latex
\documentclass{article}
\bibliographystyle{amsplain}
\begin{document}
\cite{}
 \bibliography{tex}
\end{document}
```

```latex
@book{diller97,
	    author = "Antoni Diller",
	        title = "{\LaTeX} Line by Line",
		    year = "1997",
		        edition = "1st",
			    publisher = "Wiley",
			        address = "Chichester, England"
}

@book{goossens99,
	    author = "Michel Goossens and Sebastian Rahtz",
	        title = "The {\LaTeX} Web Companion",
		    year = "1999",
		        edition = "1st",
			    publisher = "Addison-Wesley",
			        address = "Boston, Massachusetts"
}
```

Trying to `:echo Tex_FindBibFiles()` yields 

```vim
E117: Unknown function: Tex_FindBibFiles
E15: Invalid expression: Tex_FindBibFiles()
````

I have also enabled this in my `.vimrc` 
```vim
let g:Tex_Debug = 1
let g:Tex_DebugLog = "vim-latex-suite.log"
```

and this is the result log:

```vim
proj : texproject.vim: catching LatexSuiteFileType event
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
SyntaxFolds : Finished folding in   0.002920 seconds.
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
main : SetTeXOptions: sourcing maps
comp : +Tex_SetTeXCompilerTarget: setting target to [dvi] for Compiler
comp : +Tex_SetTeXCompilerTarget: setting target to [dvi] for Viewr
comp : compiler/tex.vim: sourcing this file
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
pack : :Tex_pack_updateall: split
pack : +Tex_ScanForPackages
pack : :Tex_ScanForPackages: Begining scans in [test.tex], beginline = 3
pack : :Tex_ScanForPackages: beginning scan for \usepackage lines
pack : :Tex_ScanForPackages: End scan \usepackage, detected packages = 
pack : :Tex_ScanForPackages: Beginning scan for \newcommand's
pack : :Tex_ScanForPackages: Beginning scan for \newenvironment's
pack : -Tex_ScanForPackages
pack : :Tex_pack_updateall: detected [] in first run
pack : :Tex_pack_updateall: throwing LatexSuiteScannedPackages event
pack : -Tex_pack_updateall
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
comp : +Tex_RunLaTeX, b:fragmentFile = 0
comp : Tex_RunLaTeX: compiling to target [pdf]
comp : Tex_RunLaTeX: getting dependency chain = [pdf]
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Compiler
comp : Tex_RunLaTeX: setting target to pdf
comp : Tex_RunLaTeX: compiling file once via Tex_CompileLatex
comp : Tex_CompileLatex: getting mainfname = [test.tex] from Tex_GetMainFileName
comp : Tex_CompileLatex: execing [make! test.tex]
comp : Tex_RunLaTeX: errlist = []
comp : Tex_SetupErrorWindow: mfnlog = test.log
comp : -Tex_RunLaTeX
comp : Tex_ViewLaTeX: execString = open -a Preview test.pdf
view : Tex_Complete: s:type = cite, typeoption = 
view : :Tex_Complete: using s:prefix = 
view : :Tex_FindBibFiles: 
proj : texproject.vim: catching LatexSuiteFileType event
env : envmacros.vim: Catching LatexSuiteFileType event
comp : compiler.vim: Catching LatexSuiteFileType event
fold : folding.vim: catching LatexSuiteFileType
brak : brackets.vim: Catching LatexSuiteFileType event
view : texviewer.vim: Catching LatexSuiteFileType event
main : main.vim: Catching LatexSuiteFileType event
pack : packages.vim: Catching LatexSuiteFileType event
pack : +Tex_pack_updateall
comp : +Tex_SetTeXCompilerTarget: setting target to [pdf] for Viewr
view : Tex_FindBibFiles: found bibliography command in test.tex
view : :Tex_FindBibFiles: bib command from line 5 to line 5
view : :Tex_FindBibFiles: concatenated bib command: "tex}"
view : :Tex_FindBibFiles: trying to search through [tex]
view : :Tex_FindBibFiles: returning [/Users/m/Documents/Papers/test/tex.bib
]%
```

I am on Mac OSX 10.11.5. with Vim 7.3 

Any ideas on why it is failing?

Thank you.

**Comment by gerw** [comment] 2017-09-27 11:52
I cannot reproduce your error (does it always happen or only with this tex-file?) and some details of your report really confuses me:

From your log we learn that the function `Tex_FindBibFiles` is called and correctly identifies your bib-file. (btw: is `/Users/m/Documents/Papers/test/tex.bib` the absolute path?) However, you say that `:echo Tex_FindBibFiles()` yields an error about an unknown function. This is weird.

`Tex_FindBibFiles` is called in https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/texviewer.vim#L902 and, thus, https://github.com/vim-latex/vim-latex/blob/master/ftplugin/latex-suite/texviewer.vim#L914 should create the python variable `Tex_BibFile`.

Please try the following:

- After `F9`, check whether `:py3 print(Tex_BibFile)` (or, with python 2 `:py print Tex_BibFile`. What does it yield?
- Try to create the python variable yourself: `py3 Tex_BibFile = bibtools.BibFile("/Users/m/Documents/Papers/test/tex.bib")`. Afterwards, check with `:py3 print(Tex_BibFile)` whether the variable exists.
- Try to call the python function from your system's command line:
```
cd ~/.vim/ftplugin/latex-suite/
python bibtools.py /Users/m/Documents/Papers/test/tex.bib
python3 bibtools.py /Users/m/Documents/Papers/test/tex.bib
```
You might have to adjust the path in the first line.

**Comment by miccferr** [comment] 2017-09-27 14:03
Hi,

Thank you for your reply. 

It happens with every tex file. The error confuses me as well..

- `:py print Tex_BibFile` yields:  
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'Tex_BibFile' is not defined
```
- Creating a variable results in the following error:
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/m/.vim/plugged/vim-latex/ftplugin/latex-suite/bibtools.py", line 194, in __init__
    self.addfile(f)
  File "/Users/m/.vim/plugged/vim-latex/ftplugin/latex-suite/bibtools.py", line 197, in addfile
    fields = urlopen('file://' + pathname2url(os.path.abspath(file))).read().decode('utf-8').split('@')
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 87, 
in urlopen
    return opener.open(url)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213,
 in open
    return getattr(self, name)(url)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 469,
 in open_file
    return self.open_local_file(url)
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 473,
 in open_local_file
    import mimetypes, mimetools, email.utils
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/mimetools.py", line 6
, in <module>
    import tempfile
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/tempfile.py", line 32
, in <module>
    import io as _io
  File "/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/io.py", line 51, in <
module>
    import _io
ImportError: dlopen(/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynlo
ad/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
  Referenced from: /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynloa
d/_io.so
  Expected in: flat namespace
 in /usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_io.so
```
- Calling directly the function results equally in an error:
```python
➔ python bibtools.py /Users/m/Documents/Papers/test/tex.bib
Traceback (most recent call last):
  File "bibtools.py", line 247, in <module>
    print(bf)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 4173: ordinal not in range(128)
``` 

Since this last error seems to depend on the `.bib` improper formatting, I've tested calling the function on another `.bib` file. On this second file the function works correctly, printing to standard output the content of the bibliography file, but all of the other steps fail.

**Comment by gerw** [comment] 2017-09-27 16:22
This looks like that the python within your vim is somehow broken. The error comes from the urllib library. I do not know how to handle this situation - sorry!

(However, your system's python seems to be fine)

**Comment by miccferr** [comment] 2017-09-28 13:48
I see..I'll try to investigate further then.

Thank you for your help!
m.

**Comment by gerw** [comment] 2017-09-28 14:38
Ok. Since the issue seems not be connected to latex-suite directly, I close this issue.

Please leave a comment if you find a possibility to resolve the problem.

**Closed by gerw** 2017-09-28 14:38 UTC
